// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVMPepImtoOE-8ZFg1lN2nd3_O3Az3eTg',
    appId: '1:331098322948:web:fdbd153fb59dfcf8cf9d51',
    messagingSenderId: '331098322948',
    projectId: 'instagram-tutorial-c8d0c',
    authDomain: 'instagram-tutorial-c8d0c.firebaseapp.com',
    storageBucket: 'instagram-tutorial-c8d0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoMI2xJ6r1L3ebpKLGeENXXAkcU5O4CCM',
    appId: '1:331098322948:android:b9a7279fb0dfd068cf9d51',
    messagingSenderId: '331098322948',
    projectId: 'instagram-tutorial-c8d0c',
    storageBucket: 'instagram-tutorial-c8d0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUGRQ8a4XPJMMJ8aL2V3EMJXPj_qaUriw',
    appId: '1:331098322948:ios:133baf2191899ddfcf9d51',
    messagingSenderId: '331098322948',
    projectId: 'instagram-tutorial-c8d0c',
    storageBucket: 'instagram-tutorial-c8d0c.appspot.com',
    iosClientId: '331098322948-u5f740ocv90b03fomvr01ui9pcbll84u.apps.googleusercontent.com',
    iosBundleId: 'com.kevr.instagramClone',
  );
}
